# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-08 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complain_OU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OU_name', models.TextField()),
                ('reason', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('public', 'Public'), ('restricted', 'Restricted'), ('shared', 'Shared'), ('private', 'Private')], default='public', max_length=10),
        ),
    ]
