# Generated by Django 2.0.5 on 2018-12-08 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('public', 'Public'), ('restricted', 'Restricted'), ('shared', 'Shared'), ('private', 'Private')], default='public', max_length=10),
        ),
    ]
