# Generated by Django 2.0.5 on 2018-12-09 01:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cms', '0002_auto_20181208_2358'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complain_OU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('OU_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaint', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
