# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-11 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='locked',
            field=models.BooleanField(default=False),
        ),
    ]
