# Generated by Django 2.0.5 on 2018-12-12 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_auto_20181212_0201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='isOU',
        ),
    ]
