# Generated by Django 2.0.5 on 2018-12-12 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_remove_customuser_isou'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_currently_an_OU',
            field=models.BooleanField(default=False),
        ),
    ]
